layout_spectrum: 0.7553192
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.5489362
  brandStrength: 0.2148936
  lightness: 0.4744681
  brandColors:
    - '#FFFFFF'
    - '#0D0D0D'
    - '#D0D1CF'
    - '#B4AC9A'
    - '#917653'
  rhythmicContrast: 0.5446808
typography_spectrum: 0.5021276
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Speedwear
