collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5489362
  brandStrength: 1
  lightness: 0.4744681
  brandColors:
    - '#FFFFFF'
    - '#0D0D0D'
    - '#D0D1CF'
    - '#B4AC9A'
    - '#917653'
  rhythmicContrast: 0.5446808
typography_spectrum: 0.5021276
layout_spectrum: 0.7553192
name: Speedwear
